"""Generate lazy Ruan action modules from the extracted transparent frames.

Each action is emitted into its own TypeScript module. Esbuild keeps dynamic
imports behind lazy initializers even though DSH ultimately serves one client
bundle, so only the selected action allocates its frame array. Frames are
resized to a 640px-high runtime tier before WebP encoding to reduce both bundle
weight and worst-case decoded memory while remaining crisp at normal pet sizes.
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSET = ROOT / "assets"
PET_DIR = ROOT / "src" / "pet"
ACTION_DIR = PET_DIR / "ruan-actions"
OUT = PET_DIR / "ruan-anim.ts"
TARGET_HEIGHT = 640

# These sequences add anticipation, pose holds, and recovery without adding
# more source images, which keeps the动作 readable and the bundle compact.
ACTIONS = [
    ("talk", "frames_talk", 95, [0, 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1, 0]),
    ("basketball", "frames_ball", 90, [0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1, 0]),
    ("lean", "frames_lean", 85, [0, 1, 2, 3, 4, 4, 4, 5, 6, 7, 7, 7, 6, 5, 3, 1, 0]),
    ("wave", "frames_wave", 90, [0, 1, 2, 3, 4, 5, 4, 3, 2, 3, 4, 5, 6, 7]),
]


def frame_url(path: Path) -> tuple[str, tuple[int, int]]:
    image = Image.open(path).convert("RGBA")
    if image.height != TARGET_HEIGHT:
        width = max(1, round(image.width * TARGET_HEIGHT / image.height))
        image = image.resize((width, TARGET_HEIGHT), Image.Resampling.LANCZOS)
    buffer = io.BytesIO()
    image.save(buffer, "WEBP", quality=78, method=6, alpha_quality=90)
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return "data:image/webp;base64," + encoded, image.size


def write_action_module(key: str, directory: Path) -> tuple[int, int, int]:
    files = sorted(directory.glob("frame_*.png"))
    if len(files) != 8:
        raise RuntimeError(f"Expected 8 frames for {key}, found {len(files)} in {directory}")
    encoded = [frame_url(path) for path in files]
    width, height = encoded[0][1]
    if any(size != (width, height) for _, size in encoded):
        raise RuntimeError(f"Mismatched frame sizes for {key}")

    lines = [
        "/** Generated by scripts/gen_ruan_anim_ts.py. */",
        "export const RUAN_FRAMES: readonly string[] = [",
    ]
    lines.extend(f"  '{url}'," for url, _ in encoded)
    lines.extend(["] as const;", ""])
    target = ACTION_DIR / f"{key}.ts"
    target.write_text("\n".join(lines), encoding="utf-8")
    return width, height, target.stat().st_size


def main() -> None:
    ACTION_DIR.mkdir(parents=True, exist_ok=True)
    metadata: dict[str, tuple[int, int, int, list[int]]] = {}
    total = 0
    for key, folder, frame_ms, sequence in ACTIONS:
        width, height, size = write_action_module(key, ASSET / folder)
        metadata[key] = (width, height, frame_ms, sequence)
        total += size

    keys = " | ".join(f"'{key}'" for key, *_ in ACTIONS)
    lines = [
        "/** Generated lazy metadata/loaders for the '阮启岚' action frames. */",
        f"export type RuanAnimAction = {keys};",
        "",
        "export interface RuanAnimMeta {",
        "  width: number;",
        "  height: number;",
        "  frameCount: number;",
        "  frameMs: number;",
        "  sequence: readonly number[];",
        "  durationMs: number;",
        "}",
        "",
        "export interface RuanAnim extends RuanAnimMeta {",
        "  frames: readonly string[];",
        "}",
        "",
        "export const RUAN_ANIM: Record<RuanAnimAction, RuanAnimMeta> = {",
    ]
    for key, *_ in ACTIONS:
        width, height, frame_ms, sequence = metadata[key]
        lines.extend(
            [
                f"  {key}: {{",
                f"    width: {width},",
                f"    height: {height},",
                "    frameCount: 8,",
                f"    frameMs: {frame_ms},",
                f"    sequence: {sequence},",
                f"    durationMs: {frame_ms * len(sequence)},",
                "  },",
            ]
        )
    lines.extend(
        [
            "};",
            "",
            "export const RUAN_ANIM_ACTIONS: readonly RuanAnimAction[] = ['talk', 'basketball', 'lean', 'wave'];",
            "",
            "const LOADERS: Record<RuanAnimAction, () => Promise<{ RUAN_FRAMES: readonly string[] }>> = {",
            "  talk: () => import('./ruan-actions/talk.ts'),",
            "  basketball: () => import('./ruan-actions/basketball.ts'),",
            "  lean: () => import('./ruan-actions/lean.ts'),",
            "  wave: () => import('./ruan-actions/wave.ts'),",
            "};",
            "",
            "const CACHE = new Map<RuanAnimAction, Promise<RuanAnim>>();",
            "",
            "export function loadRuanAnim(action: RuanAnimAction): Promise<RuanAnim> {",
            "  const cached = CACHE.get(action);",
            "  if (cached !== undefined) return cached;",
            "  const pending = LOADERS[action]().then(({ RUAN_FRAMES }) => ({ ...RUAN_ANIM[action], frames: RUAN_FRAMES }));",
            "  CACHE.set(action, pending);",
            "  return pending;",
            "}",
            "",
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT, OUT.stat().st_size, "bytes; action modules", total, "bytes")


if __name__ == "__main__":
    main()
